FIX: Allow user to update card details for recurring subscriptions
discourse/discourse-subscriptions pull request #123
Opened 2022-06-20 11:36 UTC by fzngagan

2022-06-24 22:13 UTC, oblakeerickson requested changes

2022-06-24 22:13 UTC, oblakeerickson commented on app/controllers/discourse_subscriptions/user/subscriptions_controller.rb
> +        customer = Customer.find(customer_id)
Let's use `find_by(id: ` here to avoid an exception. Then check if customer exists.

2022-06-24 22:13 UTC, oblakeerickson commented on app/controllers/discourse_subscriptions/user/subscriptions_controller.rb
> +      def attach_method_to_customer(customer_id, method)
Let's call this `attach_payment_method_to_customer` and rename the `method` param to `payment_method`

2022-06-28 05:42 UTC, fzngagan commented
@oblakeerickson I'll get back with the fixes by today or tomorrow. Thanks for the detailed review :)

2022-07-01 10:41 UTC, fzngagan commented on assets/javascripts/discourse/templates/user/billing/subscriptions/index.hbs
> +      <th>{{i18n "discourse_subscriptions.user.subscriptions.update_card.title"}}</th>
Done

2022-07-01 10:41 UTC, fzngagan commented on config/locales/client.en.yml
> +            title: "Update|Cancel"
Done

2022-07-01 10:41 UTC, fzngagan commented on config/locales/client.en.yml
> +            single: "Update"
Done

2022-07-01 10:41 UTC, fzngagan commented on assets/javascripts/discourse/templates/user/billing/subscriptions/card.hbs
> +
Done

2022-07-06 01:52 UTC, oblakeerickson approved these changes

2022-07-06 01:53 UTC, merged