FEATURE: Better UX for anonymous users
discourse/discourse-subscriptions pull request #25
Opened 2020-10-23 18:01 UTC by justindirose

Previously we'd throw a 404 to anonymous users hitting the `/s/product_id` route, and not really give them anywhere to go on `/s`. This PR introduces a new flow:

- Browse to one of the pages
- Instead of being presented with a 404, see content now and instead get a login button
- Login writes the `destination_url` cookie to the current URL so that upon login, they're automatically redirected back
- PROFIT (literally)

I initially tried implementing this approach server-side only using the `redirect_to_login` method, it only stopped the model calls from the front end instead of directly redirecting to `/login`. I wasn't quite able to figure out this one. However, I think this is a better solution in the long run as it keeps the user in the checkout flow vs simply bouncing them to the login page on first fire.

2020-10-26 19:04 UTC, featheredtoast commented
Make sure you're taking into account subfolder installs for the cookie redirects! Sites like http://example.com/forum should redirect to the page on the subpath accordingly, not just to the root

2020-10-26 19:05 UTC, featheredtoast requested changes
Make sure you're taking into account subfolder installs for the cookie redirects! Sites like http://example.com/forum should redirect to the page on the subpath accordingly, not just to the root

2020-10-27 16:34 UTC, justindirose commented
Good call @featheredtoast - subfolder wasn't even on my mind. I'll fix that.

2020-10-27 16:55 UTC, justindirose commented
Eh that commit might not be the best approach. Rethinking.

2020-10-27 17:51 UTC, featheredtoast commented
Yeah, sorry for not being clear, cookie path is what I was talking about @justindirose otherwise the sites that have multiple forums hosted on subpaths might have cookie conflict.

2020-10-27 20:32 UTC, justindirose commented
Okay, @featheredtoast -- I had to learn a bit more about JS regex to reason about this one. So far it seems ok. Regex assumes we're coming from either `/s` or `/s/product_id` which is safe considering this is the only place the component is used. Something feels possibly brittle or incorrect about it though I can't figure out what.

2020-10-28 14:25 UTC, pmusaraj approved these changes

2020-10-28 14:25 UTC, pmusaraj commented on test/javascripts/helpers/product-pretender.js.es6
> +    return response(model);
To save a few lines of code, this should do the same thing here: 

```
return response({ product, plans });
```

2020-10-28 14:25 UTC, pmusaraj commented on assets/javascripts/discourse/controllers/s-show.js.es6
> +  isAnonymous() {
You could probably use Ember's `not` helper and `currentUser` from the current context. So, something like: 

```
isAnonymous: not("currentUser")
```

2020-10-28 17:43 UTC, featheredtoast approved these changes
destinationUrl could probably be rewritten with `window.location.href` and safe you a call, but other than this looks good now

2020-10-28 18:30 UTC, merged